package_assets:         on
embed_assets:           off
template_function:      _.template
package_path:           packages
javascript_compressor:  yui
# compressor_options:
#   compilation_level: ADVANCED_OPTIMIZATIONS

javascripts:
  public:
    - public/javascripts/jquery-1.6.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/jquery.cycle.js
    - public/javascripts/jquery.flash.js
    - public/javascripts/jquery.cookie.js
    - public/javascripts/swfobject.js
    - public/javascripts/public_base.js
    - public/javascripts/public.js
  galleria:
    - public/javascripts/galleria/src/galleria.js
    - public/javascripts/galleria/src/plugins/galleria.history.js
  admin:
    - public/javascripts/underscore-1.1.6.js
    - public/javascripts/jquery-1.6.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/jquery.easing.1.3.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/wymeditor/jquery.wymeditor.js
    - public/javascripts/admin_base.js
    - public/javascripts/admin.js
  admin_edit:
    # - public/javascripts/backbone-0.3.3.js
    - public/javascripts/jtags.js
    - public/javascripts/wymeditor/jquery.wymeditor*.js
    - public/javascripts/fileuploader.js
    - public/javascripts/jquery.tipsy.js
    - public/javascripts/facebox.js
    - public/javascripts/jquery.multipleselectbox.js
    - public/javascripts/jquery.jBreadCrumb.1.1.js

stylesheets:
  public: 
    - public/stylesheets/public_grid.css
    - public/stylesheets/public_base.css
    - public/stylesheets/public.css
  admin:
    - public/stylesheets/admin_grid.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/jquery-ui.css
    - public/stylesheets/multipleselectbox.css
    - public/stylesheets/tipsy.css
    - public/stylesheets/facebox.css
    - public/stylesheets/jBreadCrumb.css
    - public/stylesheets/admin_base.css
    - public/stylesheets/admin.css
  admin_edit:
  galleria:
    - public/stylesheets/galleria.css